alter table public.organisations
  add column if not exists created_by uuid references auth.users(id) on delete set null;

alter table public.sites
  add column if not exists created_by uuid references auth.users(id) on delete set null;

create table if not exists public.site_invitations (
  id uuid primary key default gen_random_uuid(),
  organisation_id uuid not null references public.organisations(id) on delete cascade,
  site_id uuid not null references public.sites(id) on delete cascade,
  email text not null,
  app_role text not null,
  full_name text,
  status text not null default 'pending',
  invited_by uuid not null references auth.users(id) on delete restrict,
  auth_user_id uuid references auth.users(id) on delete set null,
  expires_at timestamptz not null default (now() + interval '24 hours'),
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint site_invitations_status_check check (status in ('pending','accepted','cancelled','failed','expired')),
  constraint site_invitations_role_check check (app_role in (
    'site_admin','maintenance_manager','maintenance_planner','reliability_engineer',
    'engineer','production_manager','operator','contractor_admin','contractor_engineer'
  ))
);

create unique index if not exists site_invitations_pending_email_site_idx
  on public.site_invitations(site_id, lower(email))
  where status = 'pending';

create table if not exists public.site_admin_audit_log (
  id bigint generated by default as identity primary key,
  organisation_id uuid not null references public.organisations(id) on delete cascade,
  site_id uuid not null references public.sites(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  target_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  previous_value jsonb,
  new_value jsonb,
  created_at timestamptz not null default now()
);

alter table public.site_invitations enable row level security;
alter table public.site_admin_audit_log enable row level security;

drop policy if exists site_invitations_select_admins on public.site_invitations;
create policy site_invitations_select_admins
on public.site_invitations
for select
to authenticated
using (
  exists (
    select 1
    from public.user_site_access access_row
    where access_row.user_id = (select auth.uid())
      and access_row.site_id = site_invitations.site_id
      and access_row.organisation_id = site_invitations.organisation_id
      and access_row.active
      and access_row.app_role in ('site_owner','site_admin','vorta_admin')
  )
);

drop policy if exists site_admin_audit_log_select_admins on public.site_admin_audit_log;
create policy site_admin_audit_log_select_admins
on public.site_admin_audit_log
for select
to authenticated
using (
  exists (
    select 1
    from public.user_site_access access_row
    where access_row.user_id = (select auth.uid())
      and access_row.site_id = site_admin_audit_log.site_id
      and access_row.organisation_id = site_admin_audit_log.organisation_id
      and access_row.active
      and access_row.app_role in ('site_owner','site_admin','vorta_admin')
  )
);

grant select on public.site_invitations to authenticated;
grant select on public.site_admin_audit_log to authenticated;

create or replace function public.vorta_validate_user_site_access_row()
returns trigger
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
as $function$
declare
  v_site_organisation_id uuid;
  v_profile_organisation_id uuid;
  v_profile_role text;
  v_app_role text;
begin
  v_app_role := lower(replace(replace(coalesce(new.app_role, ''), '-', '_'), ' ', '_'));
  v_app_role := case v_app_role
    when 'owner' then 'site_owner'
    when 'siteowner' then 'site_owner'
    when 'admin' then 'site_admin'
    when 'manager' then 'maintenance_manager'
    when 'planner' then 'maintenance_planner'
    when 'maintenance_engineer' then 'engineer'
    when 'production_operator' then 'operator'
    when 'contractor' then 'contractor_admin'
    when 'contractor_company_admin' then 'contractor_admin'
    else v_app_role
  end;

  if v_app_role not in (
    'vorta_admin','site_owner','site_admin','maintenance_manager','maintenance_planner',
    'reliability_engineer','engineer','production_manager','operator',
    'contractor_admin','contractor_engineer'
  ) then
    raise exception 'Unsupported Vorta site role: %', new.app_role using errcode = '22023';
  end if;

  new.app_role := v_app_role;
  if not new.active then new.is_default := false; end if;

  select site.organisation_id into v_site_organisation_id
  from public.sites site where site.id = new.site_id;
  if v_site_organisation_id is null then raise exception 'Unknown site: %', new.site_id; end if;
  if v_site_organisation_id <> new.organisation_id then
    raise exception 'Site % does not belong to organisation %', new.site_id, new.organisation_id;
  end if;

  select profile.organisation_id,
         lower(replace(replace(coalesce(profile.role, ''), '-', '_'), ' ', '_'))
    into v_profile_organisation_id, v_profile_role
  from public.profiles profile
  where profile.id = new.user_id;

  if not found then raise exception 'User profile was not found: %', new.user_id; end if;
  if v_profile_role <> 'vorta_admin' and v_profile_organisation_id is distinct from new.organisation_id then
    raise exception 'User % does not belong to organisation %', new.user_id, new.organisation_id;
  end if;

  new.updated_at := now();
  return new;
end;
$function$;

create or replace function public.vorta_can_manage_site(p_site_id uuid)
returns boolean
language plpgsql
stable security definer
set search_path to 'pg_catalog', 'public'
as $function$
declare
  v_jwt_role text := coalesce(auth.jwt() ->> 'role', '');
  v_profile_role text;
  v_site_role text;
begin
  if v_jwt_role = 'service_role' then return true; end if;
  if not public.vorta_has_site_access(p_site_id, false) then return false; end if;

  select lower(replace(replace(coalesce(access_row.app_role, ''), '-', '_'), ' ', '_'))
    into v_site_role
  from public.user_site_access access_row
  where access_row.user_id = auth.uid()
    and access_row.site_id = p_site_id
    and access_row.active
  limit 1;

  if v_site_role in ('site_owner','site_admin','maintenance_manager','maintenance_planner','reliability_engineer') then
    return true;
  end if;

  select lower(replace(replace(coalesce(profile.role, ''), '-', '_'), ' ', '_'))
    into v_profile_role
  from public.profiles profile where profile.id = auth.uid();

  return v_profile_role = 'vorta_admin';
end;
$function$;

create or replace function public.vorta_bootstrap_site_owner(
  p_full_name text,
  p_organisation_name text,
  p_industry text,
  p_country text,
  p_site_name text,
  p_site_location text default null
)
returns table(organisation_id uuid, site_id uuid, app_role text)
language plpgsql
security definer
set search_path to 'pg_catalog', 'public', 'auth'
as $function$
declare
  v_user_id uuid := auth.uid();
  v_email text;
  v_confirmed_at timestamptz;
  v_existing_org uuid;
  v_org_id uuid;
  v_site_id uuid;
  v_full_name text := nullif(btrim(p_full_name), '');
  v_org_name text := nullif(btrim(p_organisation_name), '');
  v_site_name text := nullif(btrim(p_site_name), '');
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;

  select users.email, users.email_confirmed_at
    into v_email, v_confirmed_at
  from auth.users users
  where users.id = v_user_id;

  if v_email is null or v_confirmed_at is null then
    raise exception 'A verified email address is required before creating a Vorta site' using errcode = '28000';
  end if;

  if v_full_name is null or length(v_full_name) > 120 then raise exception 'Your name is required'; end if;
  if v_org_name is null or length(v_org_name) > 160 then raise exception 'Organisation name is required'; end if;
  if v_site_name is null or length(v_site_name) > 160 then raise exception 'Site name is required'; end if;

  if exists (select 1 from public.user_site_access a where a.user_id = v_user_id and a.active) then
    raise exception 'This account already has an active Vorta site assignment';
  end if;

  select profile.organisation_id into v_existing_org
  from public.profiles profile where profile.id = v_user_id;

  if v_existing_org is not null then
    raise exception 'This account is already attached to a Vorta organisation';
  end if;

  insert into public.organisations(name, type, industry, location, status, created_by)
  values (v_org_name, 'site_customer', nullif(btrim(p_industry), ''), nullif(btrim(p_country), ''), 'active', v_user_id)
  returning id into v_org_id;

  insert into public.sites(organisation_id, name, address, region, created_by)
  values (v_org_id, v_site_name, nullif(btrim(p_site_location), ''), nullif(btrim(p_country), ''), v_user_id)
  returning id into v_site_id;

  insert into public.profiles(id, organisation_id, full_name, role)
  values (v_user_id, v_org_id, v_full_name, 'site_owner')
  on conflict (id) do update set
    organisation_id = excluded.organisation_id,
    full_name = excluded.full_name,
    role = 'site_owner',
    updated_at = now();

  insert into public.user_site_access(user_id, organisation_id, site_id, app_role, is_default, active)
  values (v_user_id, v_org_id, v_site_id, 'site_owner', true, true);

  insert into public.site_admin_audit_log(organisation_id, site_id, actor_user_id, target_user_id, action, new_value)
  values (v_org_id, v_site_id, v_user_id, v_user_id, 'SITE_CREATED', jsonb_build_object('role','site_owner','email',lower(v_email)));

  return query select v_org_id, v_site_id, 'site_owner'::text;
end;
$function$;

revoke all on function public.vorta_bootstrap_site_owner(text,text,text,text,text,text) from public, anon;
grant execute on function public.vorta_bootstrap_site_owner(text,text,text,text,text,text) to authenticated;

create or replace function public.vorta_accept_site_invitation(
  p_invitation_id uuid,
  p_full_name text default null
)
returns table(organisation_id uuid, site_id uuid, app_role text)
language plpgsql
security definer
set search_path to 'pg_catalog', 'public', 'auth'
as $function$
declare
  v_user_id uuid := auth.uid();
  v_email text;
  v_confirmed_at timestamptz;
  v_inv public.site_invitations%rowtype;
  v_existing_org uuid;
  v_default boolean;
begin
  if v_user_id is null then raise exception 'Authentication required' using errcode = '28000'; end if;

  select users.email, users.email_confirmed_at into v_email, v_confirmed_at
  from auth.users users where users.id = v_user_id;
  if v_email is null or v_confirmed_at is null then raise exception 'A verified email address is required'; end if;

  select * into v_inv
  from public.site_invitations invitation
  where invitation.id = p_invitation_id
  for update;

  if not found then raise exception 'Vorta invitation not found'; end if;
  if v_inv.status <> 'pending' then raise exception 'This Vorta invitation is no longer active'; end if;
  if v_inv.expires_at <= now() then
    update public.site_invitations set status='expired', updated_at=now() where id=v_inv.id;
    raise exception 'This Vorta invitation has expired';
  end if;
  if lower(v_inv.email) <> lower(v_email) then raise exception 'This invitation was issued to a different email address'; end if;

  select profile.organisation_id into v_existing_org
  from public.profiles profile where profile.id = v_user_id;
  if v_existing_org is not null and v_existing_org <> v_inv.organisation_id then
    raise exception 'This account belongs to a different Vorta organisation';
  end if;

  v_default := not exists (select 1 from public.user_site_access a where a.user_id=v_user_id and a.active);

  insert into public.profiles(id, organisation_id, full_name, role)
  values (v_user_id, v_inv.organisation_id, coalesce(nullif(btrim(p_full_name),''), v_inv.full_name), v_inv.app_role)
  on conflict (id) do update set
    organisation_id = excluded.organisation_id,
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    role = case when public.profiles.organisation_id is null then excluded.role else public.profiles.role end,
    updated_at = now();

  insert into public.user_site_access(user_id, organisation_id, site_id, app_role, is_default, active)
  values (v_user_id, v_inv.organisation_id, v_inv.site_id, v_inv.app_role, v_default, true)
  on conflict (user_id, site_id) do update set
    organisation_id=excluded.organisation_id,
    app_role=excluded.app_role,
    active=true,
    is_default=case when v_default then true else public.user_site_access.is_default end,
    updated_at=now();

  update public.site_invitations
  set status='accepted', auth_user_id=v_user_id, accepted_at=now(), updated_at=now()
  where id=v_inv.id;

  insert into public.site_admin_audit_log(organisation_id, site_id, actor_user_id, target_user_id, action, new_value)
  values (v_inv.organisation_id, v_inv.site_id, v_user_id, v_user_id, 'INVITATION_ACCEPTED', jsonb_build_object('role',v_inv.app_role,'email',lower(v_email)));

  return query select v_inv.organisation_id, v_inv.site_id, v_inv.app_role;
end;
$function$;

revoke all on function public.vorta_accept_site_invitation(uuid,text) from public, anon;
grant execute on function public.vorta_accept_site_invitation(uuid,text) to authenticated;
